language: node_js
node_js:
  - stable
cache:
  directories:
    - node_modules
script:
  - npm run build
deploy:
  provider: heroku
  app: sell--ticket
  api_key:
    secure: lhpAOSz7EYFpeE8K/BMoDWnmhi0h1SCwHQtjlsDk7s4By9rDWjYK0S72m5CvTBRhX8EsXXgzIQC+SxRZOd7hSuJBp1xsf3zlKYK0CaB4+RVKshw2y010y1usayA9E5fqv6WywAM6KiD5iC6KfdDhx+OURGJpLRPGHkl1xHkLPtfdLYfUYbUgbe8+mekQAfIbALFaaH/ekzxT3oCZ8sIAtH09mTjQrarY15Te5wtIkfbj5QPC0TDE/UH7UEES9TtEWwF9iY9Aake5fTXH/fy64Tt+qrju/5sZxPQm3ql7WxWGnZ3UIqt4NprsdWH/C4b6tz/u2VePQgWBNFmC9K6uxmvr8hYrGql1hMpALord0YObvB8SYSw7FN50bAG0tXS7ld7j8gfMGt6mvcNWhvi3VppUg2dRb8SbHo18gZsBSVRrVGh39Uvs5olnbkqTVZH87QZ4B8LA4EwtWcPcFB0A5Y/lO1idYbYP6DaSIVmYhBliXWK86ZP4ALR/SakViE8ew0iReLfd4LnBzPwDCJIPyRMHv5Wt9lfplTUeYCRtbY4c4xGV4ZuGDeQfzShoH294as1oEOpdZXdJ3dkCnFJ4yRCudljoymIbrrfBXk2v8+xQdKgX/V7wu11CK1YosaK8Y9xbKl6dEuto2TdtO6dTUK+jL1DpGj7oifVvfdLZJGU=
true:
  branch: master

notifications:
  webhooks: https://outlook.office.com/webhook/2235fdbc-cc22-4c73-9e4e-85867a7dd193@63886f82-1054-44ed-abf1-1f94bb74985a/TravisCI/b403949f99074f3784a8503ee9caf239/57fa2627-140e-4d70-8dc3-90202f532880
